# Render deployment configuration
services:
  # Backend API Service
  - type: web
    name: contentiq-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/health

databases:
  # If using Render's managed database (optional)
  # - name: contentiq-mongodb
  #   plan: free
